import { PrismaClient } from '@prisma/client'
import bcrypt from 'bcryptjs'

const prisma = new PrismaClient()

async function main() {
  console.log('Starting seed...')

  // Create admin user
  const hashedPassword = await bcrypt.hash('admin123', 10)
  
  const admin = await prisma.user.upsert({
    where: { email: 'admin@example.com' },
    update: {},
    create: {
      email: 'admin@example.com',
      name: 'Admin',
      password: hashedPassword,
      role: 'ADMIN',
      emailVerified: new Date(),
    },
  })

  console.log('Admin user created:', admin.email)

  // Create categories
  const categories = await Promise.all([
    prisma.category.upsert({
      where: { slug: 'pasta-halal' },
      update: {},
      create: {
        name: 'Pasta Halal',
        slug: 'pasta-halal',
        description: 'Produk pasta perisa dan pewarna bersertifikat Halal MUI',
        halal: true,
      },
    }),
    prisma.category.upsert({
      where: { slug: 'pasta-non-halal' },
      update: {},
      create: {
        name: 'Pasta Non-Halal',
        slug: 'pasta-non-halal',
        description: 'Produk pasta perisa dan pewarna (belum bersertifikat halal)',
        halal: false,
      },
    }),
  ])

  console.log('Categories created:', categories.length)

  // Create sample products - Pasta Halal
  const halalCategory = categories.find(c => c.slug === 'pasta-halal')!
  const nonHalalCategory = categories.find(c => c.slug === 'pasta-non-halal')!

  // Helper to build variant structure
  const buildVariants = (sizes: string[]) => {
    const priceMap: Record<string, number> = {
      '30g': 38000,
      '100g': 85000,
      '1kg': 650000
    }
    return JSON.stringify([{
      name: 'Ukuran',
      options: sizes.map(s => `${s} - Rp ${priceMap[s]?.toLocaleString('id-ID') || '0'}`)
    }])
  }

  const buildImages = (productName: string, sizes: string[]) => {
    return JSON.stringify(sizes.map(size => `/assets/products/${size}/${productName}.png`))
  }

  const products = [
    // ==================== PRODUK HALAL - 3 Ukuran ====================
    {
      name: 'Perisa Alpukat dan Pewarna',
      slug: 'pasta-alpukat',
      description: 'Pasta perisa alpukat dengan pewarna alami, cocok untuk kue, roti, dan berbagai kreasi kuliner. Bersertifikat Halal MUI dan BPOM.',
      price: 38000,
      stock: 100,
      featured: false,
      brand: 'Golden Brown',
      sku: 'GB-ALPUKAT-30',
  weight: 0.03,
  image: '/assets/products/30g/Alpukat.png',
      categoryId: halalCategory.id,
      discount: 5,
      discountPrice: 36100,
    },
    {
      name: 'Perisa Anggur dan Pewarna',
      slug: 'pasta-anggur',
      description: 'Pasta perisa anggur dengan pewarna ungu cerah untuk kreasi kue menarik. Halal MUI.',
      price: 38000,
      stock: 100,
      featured: false,
      brand: 'Golden Brown',
      sku: 'GB-GRAPE-30',
  weight: 0.03,
  image: '/assets/products/100g/Anggur.png',
      categoryId: halalCategory.id,
      discount: 5,
      discountPrice: 36100,
    },
    {
      name: 'Perisa Blueberi dan Pewarna',
      slug: 'pasta-blueberi',
      description: 'Pasta perisa blueberi dengan pewarna untuk hasil kue yang menarik. Halal MUI dan terdaftar BPOM.',
      price: 39000,
      stock: 100,
      featured: true,
      brand: 'Golden Brown',
      sku: 'GB-BLUEBERRY-30',
  weight: 0.03,
  image: '/assets/products/30g/Blueberi.png',
      categoryId: halalCategory.id,
      discount: 5,
      discountPrice: 37050,
    },
    {
      name: 'Perisa Buttermilk Oil',
      slug: 'pasta-buttermilk-oil',
      description: 'Pasta perisa buttermilk oil untuk cake lembut dan moist. Halal MUI.',
      price: 40000,
      stock: 100,
      featured: false,
      brand: 'Golden Brown',
      sku: 'GB-BUTTERMILK-30',
  weight: 0.03,
  image: '/assets/products/30g/Buttermilk Oil.png',
      categoryId: halalCategory.id,
      discount: 5,
      discountPrice: 38000,
    },
    {
      name: 'Perisa Karamel dan Pewarna',
      slug: 'pasta-karamel',
      description: 'Pasta perisa karamel yang memberikan aroma dan rasa manis yang khas. Halal MUI.',
      price: 38500,
      stock: 100,
      featured: false,
      brand: 'Golden Brown',
      sku: 'GB-CARAMEL-30',
  weight: 0.03,
  image: '/assets/products/30g/Caramel.png',
      categoryId: halalCategory.id,
      discount: 5,
      discountPrice: 36575,
    },
    {
      name: 'Perisa Kopi dan Pewarna (COFFEE BOY)',
      slug: 'pasta-coffee-boy',
      description: 'Pasta perisa kopi premium Coffee Boy untuk berbagai kreasi cake dan bakery. Halal MUI dan BPOM.',
      price: 42000,
      stock: 100,
      featured: true,
      brand: 'Golden Brown',
      sku: 'GB-COFFEEBOY-30',
  weight: 0.03,
  image: '/assets/products/100g/Coffee Boy.png',
      categoryId: halalCategory.id,
      discount: 5,
      discountPrice: 39900,
    },
    {
      name: 'Perisa Cokelat Blackforest dan Pewarna',
      slug: 'pasta-cokelat-blackforest',
      description: 'Pasta perisa cokelat blackforest dengan rasa yang kaya dan pewarna cokelat pekat. Halal MUI.',
      price: 43000,
      stock: 100,
      featured: true,
      brand: 'Golden Brown',
      sku: 'GB-BLACKFOREST-30',
  weight: 0.03,
  image: '/assets/products/30g/Cokelat Blackforest.png',
      categoryId: halalCategory.id,
      discount: 5,
      discountPrice: 40850,
    },
    {
      name: 'Perisa Cokelat dan Pewarna (Flavour & Color)',
      slug: 'pasta-cokelat-flavocol',
      description: 'Pasta perisa cokelat premium dengan kombinasi pewarna sempurna. Halal MUI dan BPOM.',
      price: 39500,
      stock: 100,
      featured: true,
      brand: 'Golden Brown',
      sku: 'GB-CHOCO-FLAVOCOL-30',
  weight: 0.03,
  image: '/assets/products/100g/Cokelat Flavocol.png',
      categoryId: halalCategory.id,
      discount: 5,
      discountPrice: 37525,
    },
    {
      name: 'Perisa Cokelat dan Pewarna',
      slug: 'pasta-cokelat',
      description: 'Pasta perisa cokelat standar yang cocok untuk berbagai jenis kue. Halal MUI.',
      price: 39000,
      stock: 100,
      featured: true,
      brand: 'Golden Brown',
      sku: 'GB-CHOCO-30',
  weight: 0.03,
  image: '/assets/products/30g/Cokelat.png',
      categoryId: halalCategory.id,
      discount: 5,
      discountPrice: 37050,
    },
    {
      name: 'Perisa Durian dan Pewarna',
      slug: 'pasta-durian',
      description: 'Pasta perisa durian asli untuk kue dan dessert. Aroma dan rasa durian yang khas. Halal MUI.',
      price: 40000,
      stock: 100,
      featured: false,
      brand: 'Golden Brown',
      sku: 'GB-DURIAN-30',
  weight: 0.03,
  image: '/assets/products/30g/Durian.png',
      categoryId: halalCategory.id,
      discount: 5,
      discountPrice: 38000,
    },
    {
      name: 'Perisa Frambozen dan Pewarna',
      slug: 'pasta-frambozen',
      description: 'Pasta perisa raspberry (frambozen) dengan warna merah menarik. Halal MUI dan BPOM.',
      price: 41000,
      stock: 100,
      featured: false,
      brand: 'Golden Brown',
      sku: 'GB-RASPBERRY-30',
  weight: 0.03,
  image: '/assets/products/30g/Frambozen.png',
      categoryId: halalCategory.id,
      discount: 5,
      discountPrice: 38950,
    },
    {
      name: 'Perisa Gula Aren dan Pewarna',
      slug: 'pasta-gula-aren',
      description: 'Pasta perisa gula aren dengan aroma khas gula merah asli. Halal MUI.',
      price: 39000,
      stock: 100,
      featured: false,
      brand: 'Golden Brown',
      sku: 'GB-PALMSUGAR-30',
  weight: 0.03,
  image: '/assets/products/30g/Gula Aren.png',
      categoryId: halalCategory.id,
      discount: 5,
      discountPrice: 37050,
    },
    {
      name: 'Perisa Jeruk dan Pewarna',
      slug: 'pasta-jeruk',
      description: 'Pasta perisa jeruk dengan rasa citrus yang segar dan pewarna orange. Halal MUI dan BPOM.',
      price: 37500,
      stock: 100,
      featured: false,
      brand: 'Golden Brown',
      sku: 'GB-ORANGE-30',
  weight: 0.03,
  image: '/assets/products/100g/Jeruk.png',
      categoryId: halalCategory.id,
      discount: 5,
      discountPrice: 35625,
    },
    {
      name: 'Perisa Kelapa',
      slug: 'pasta-kelapa',
      description: 'Pasta perisa kelapa dengan aroma santan segar untuk kreasi kue tradisional. Halal MUI dan BPOM.',
      price: 37000,
      stock: 100,
      featured: false,
      brand: 'Golden Brown',
      sku: 'GB-COCONUT-30',
  weight: 0.03,
  image: '/placeholder-product.jpg',
      categoryId: halalCategory.id,
      discount: 5,
      discountPrice: 35150,
    },
    {
      name: 'Perisa Kopi Moka Plus',
      slug: 'pasta-kopi-moka-plus',
      description: 'Pasta perisa kopi moka plus dengan rasa kopi yang lebih kaya. Halal MUI dan BPOM.',
      price: 41000,
      stock: 100,
      featured: false,
      brand: 'Golden Brown',
      sku: 'GB-MOKAPLUS-30',
  weight: 0.03,
  image: '/assets/products/100g/Kopi Moka Plus.png',
      categoryId: halalCategory.id,
      discount: 5,
      discountPrice: 38950,
    },
    {
      name: 'Perisa Kopi Noir',
      slug: 'pasta-kopi-noir',
      description: 'Pasta perisa kopi noir dengan rasa kopi yang kuat dan premium. Halal MUI dan BPOM.',
      price: 42000,
      stock: 100,
      featured: false,
      brand: 'Golden Brown',
      sku: 'GB-COFFENOIR-30',
  weight: 0.03,
  image: '/placeholder-product.jpg',
      categoryId: halalCategory.id,
      discount: 5,
      discountPrice: 39900,
    },
    {
      name: 'Perisa Leci',
      slug: 'pasta-leci',
      description: 'Pasta perisa leci dengan rasa buah leci yang manis dan segar. Halal MUI dan BPOM.',
      price: 39000,
      stock: 100,
      featured: false,
      brand: 'Golden Brown',
      sku: 'GB-LYCHEE-30',
  weight: 0.03,
  image: '/assets/products/30g/Leci.png',
      categoryId: halalCategory.id,
      discount: 5,
      discountPrice: 37050,
    },
    {
      name: 'Perisa Alami Lemon',
      slug: 'pasta-lemon',
      description: 'Pasta perisa lemon alami dengan aroma segar jeruk lemon. Halal MUI.',
      price: 38000,
      stock: 100,
      featured: false,
      brand: 'Golden Brown',
      sku: 'GB-LEMON-30',
  weight: 0.03,
  image: '/assets/products/100g/Lemon.png',
      categoryId: halalCategory.id,
      discount: 5,
      discountPrice: 36100,
    },
    {
      name: 'Perisa Mangga dan Pewarna',
      slug: 'pasta-mangga',
      description: 'Pasta perisa mangga dengan pewarna kuning cerah untuk kreasi tropical. Halal MUI.',
      price: 37500,
      stock: 100,
      featured: true,
      brand: 'Golden Brown',
      sku: 'GB-MANGO-30',
  weight: 0.03,
  image: '/assets/products/30g/Mangga.png',
      categoryId: halalCategory.id,
      discount: 5,
      discountPrice: 35625,
    },
    {
      name: 'Perisa Melon dan Pewarna',
      slug: 'pasta-melon',
      description: 'Pasta perisa melon dengan warna hijau segar untuk kue dan dessert. Halal MUI dan BPOM.',
      price: 38000,
      stock: 100,
      featured: false,
      brand: 'Golden Brown',
      sku: 'GB-MELON-30',
  weight: 0.03,
  image: '/assets/products/30g/Melon.png',
      categoryId: halalCategory.id,
      discount: 5,
      discountPrice: 36100,
    },
    {
      name: 'Perisa Moka dan Pewarna',
      slug: 'pasta-moka',
      description: 'Pasta perisa moka dengan rasa kopi yang nikmat untuk cake dan bakery. Halal MUI.',
      price: 39000,
      stock: 100,
      featured: true,
      brand: 'Golden Brown',
      sku: 'GB-MOCHA-30',
  weight: 0.03,
  image: '/assets/products/30g/Moka.png',
      categoryId: halalCategory.id,
      discount: 5,
      discountPrice: 37050,
    },
    {
      name: 'Perisa Moka Hopyes dan Pewarna',
      slug: 'pasta-moka-hopyes',
      description: 'Pasta perisa moka hopyes premium dengan kombinasi kopi dan cokelat. Halal MUI dan BPOM.',
      price: 42000,
      stock: 100,
      featured: true,
      brand: 'Golden Brown',
      sku: 'GB-MOKAHOPYES-30',
  weight: 0.03,
  image: '/assets/products/30g/Moka Hopyes.png',
      categoryId: halalCategory.id,
      discount: 5,
      discountPrice: 39900,
    },
    {
      name: 'Perisa Nanas dan Pewarna',
      slug: 'pasta-nanas',
      description: 'Pasta perisa nanas dengan rasa tropical yang segar dan pewarna kuning. Halal MUI dan BPOM.',
      price: 38000,
      stock: 100,
      featured: false,
      brand: 'Golden Brown',
      sku: 'GB-PINEAPPLE-30',
  weight: 0.03,
  image: '/assets/products/30g/Nanas.png',
      categoryId: halalCategory.id,
      discount: 5,
      discountPrice: 36100,
    },
    {
      name: 'Perisa Nangka dan Pewarna',
      slug: 'pasta-nangka',
      description: 'Pasta perisa nangka dengan aroma khas buah nangka matang. Halal MUI.',
      price: 38500,
      stock: 100,
      featured: false,
      brand: 'Golden Brown',
      sku: 'GB-JACKFRUIT-30',
  weight: 0.03,
  image: '/assets/products/30g/Nangka.png',
      categoryId: halalCategory.id,
      discount: 5,
      discountPrice: 36575,
    },
    {
      name: 'Pewarna Bakar (N-Bakar)',
      slug: 'pewarna-bakar',
      description: 'Pewarna khusus untuk cake bakar dengan hasil warna cokelat alami. Halal MUI dan BPOM.',
      price: 35000,
      stock: 100,
      featured: false,
      brand: 'Golden Brown',
      sku: 'GB-NBAKAR-30',
  weight: 0.03,
  image: '/assets/products/30g/N-Bakar.png',
      categoryId: halalCategory.id,
      discount: 5,
      discountPrice: 33250,
    },
    {
      name: 'Pewarna Blackforest (N-Blackforest)',
      slug: 'pewarna-blackforest',
      description: 'Pewarna khusus untuk cake blackforest dengan warna cokelat pekat. Halal MUI.',
      price: 36000,
      stock: 100,
      featured: false,
      brand: 'Golden Brown',
      sku: 'GB-NBLACKFOREST-30',
  weight: 0.03,
  image: '/assets/products/30g/N-Blackforest.png',
      categoryId: halalCategory.id,
      discount: 5,
      discountPrice: 34200,
    },
    {
      name: 'Pewarna Buttercream (N-Buttercream)',
      slug: 'pewarna-buttercream',
      description: 'Pewarna untuk buttercream dengan hasil warna yang stabil. Halal MUI dan BPOM.',
      price: 35500,
      stock: 100,
      featured: false,
      brand: 'Golden Brown',
      sku: 'GB-NBUTTERCREAM-30',
  weight: 0.03,
  image: '/assets/products/30g/N-Buttercream.png',
      categoryId: halalCategory.id,
      discount: 5,
      discountPrice: 33725,
    },
    {
      name: 'Pewarna Semprot (N-Semprot)',
      slug: 'pewarna-semprot',
      description: 'Pewarna khusus untuk spray gun dengan hasil warna merata. Halal MUI.',
      price: 37000,
      stock: 100,
      featured: false,
      brand: 'Golden Brown',
      sku: 'GB-NSEMPROT-30',
  weight: 0.03,
  image: '/assets/products/30g/N-Semprot.png',
      categoryId: halalCategory.id,
      discount: 5,
      discountPrice: 35150,
    },
    {
      name: 'Perisa Pandan dan Pewarna',
      slug: 'pasta-pandan',
      description: 'Pasta perisa pandan dengan aroma khas dan pewarna hijau natural. Best seller! Halal MUI.',
      price: 38500,
      stock: 100,
      featured: true,
      brand: 'Golden Brown',
      sku: 'GB-PANDAN-30',
  weight: 0.03,
  image: '/assets/products/30g/Pandan.png',
      categoryId: halalCategory.id,
      discount: 5,
      discountPrice: 36575,
    },
    {
      name: 'Perisa Pisang Ambon',
      slug: 'pasta-pisang-ambon',
      description: 'Pasta perisa pisang ambon dengan aroma pisang yang khas dan manis. Halal MUI dan BPOM.',
      price: 37500,
      stock: 100,
      featured: false,
      brand: 'Golden Brown',
      sku: 'GB-BANANA-30',
  weight: 0.03,
  image: '/assets/products/30g/Pisang Ambon.png',
      categoryId: halalCategory.id,
      discount: 5,
      discountPrice: 35625,
    },
    {
      name: 'Perisa Redvelvet dan Pewarna',
      slug: 'pasta-red-velvet',
      description: 'Pasta perisa red velvet dengan pewarna merah pekat untuk cake mewah. Halal MUI.',
      price: 41000,
      stock: 100,
      featured: true,
      brand: 'Golden Brown',
      sku: 'GB-REDVELVET-30',
  weight: 0.03,
  image: '/assets/products/30g/Red Velvet.png',
      categoryId: halalCategory.id,
      discount: 5,
      discountPrice: 38950,
    },
    {
      name: 'Perisa Stroberi dan Pewarna',
      slug: 'pasta-stroberi',
      description: 'Pasta perisa strawberry dengan pewarna pink/merah untuk kreasi manis. Halal MUI dan BPOM.',
      price: 38000,
      stock: 100,
      featured: true,
      brand: 'Golden Brown',
      sku: 'GB-STRAWBERRY-30',
  weight: 0.03,
  image: '/assets/products/30g/Stroberi.png',
      categoryId: halalCategory.id,
      discount: 5,
      discountPrice: 36100,
    },
    {
      name: 'Perisa Susu',
      slug: 'pasta-susu',
      description: 'Pasta perisa susu murni untuk kreasi cake dan bakery yang lembut. Halal MUI.',
      price: 36000,
      stock: 100,
      featured: true,
      brand: 'Golden Brown',
      sku: 'GB-MILK-30',
  weight: 0.03,
  image: '/assets/products/30g/Susu.png',
      categoryId: halalCategory.id,
      discount: 5,
      discountPrice: 34200,
    },
    {
      name: 'Perisa Talas dan Pewarna',
      slug: 'pasta-talas',
      description: 'Pasta perisa talas dengan pewarna ungu natural untuk kreasi kue unik. Halal MUI.',
      price: 39000,
      stock: 100,
      featured: false,
      brand: 'Golden Brown',
      sku: 'GB-TARO-30',
  weight: 0.03,
  image: '/assets/products/30g/Talas.png',
      categoryId: halalCategory.id,
      discount: 5,
      discountPrice: 37050,
    },
    {
      name: 'Perisa Teh Hijau dan Pewarna',
      slug: 'pasta-green-tea',
      description: 'Pasta perisa green tea (matcha) dengan pewarna hijau natural. Halal MUI dan BPOM.',
      price: 40000,
      stock: 100,
      featured: true,
      brand: 'Golden Brown',
      sku: 'GB-GREENTEA-30',
  weight: 0.03,
  image: '/assets/products/30g/Teh Hijau.png',
      categoryId: halalCategory.id,
      discount: 5,
      discountPrice: 38000,
    },
    {
      name: 'Perisa Tiramisu',
      slug: 'pasta-tiramisu',
      description: 'Pasta perisa tiramisu dengan kombinasi kopi dan cream yang sempurna. Halal MUI dan BPOM.',
      price: 43000,
      stock: 100,
      featured: true,
      brand: 'Golden Brown',
      sku: 'GB-TIRAMISU-30',
  weight: 0.03,
  image: '/assets/products/30g/Tiramisu.png',
      categoryId: halalCategory.id,
      discount: 5,
      discountPrice: 40850,
    },
    {
      name: 'Perisa Tutty Fruity',
      slug: 'pasta-tutty-fruity',
      description: 'Pasta perisa tutty fruity dengan kombinasi berbagai buah tropis. Halal MUI.',
      price: 39500,
      stock: 100,
      featured: false,
      brand: 'Golden Brown',
      sku: 'GB-TUTTYFRUITY-30',
  weight: 0.03,
  image: '/assets/products/30g/Tutty Fruity.png',
      categoryId: halalCategory.id,
      discount: 5,
      discountPrice: 37525,
    },

    // PRODUK NON-HALAL
    {
      name: 'Perisa Rum Bakar',
      slug: 'pasta-rum-bakar',
      description: 'Pasta perisa rum untuk cake bakar dengan aroma khas. Belum bersertifikat halal.',
      price: 45000,
      stock: 100,
      featured: false,
      brand: 'Golden Brown',
      sku: 'GB-RUMBAKAR-30',
      weight: 0.03,
  image: '/assets/products/100g/Rum Bakar.png',
      categoryId: nonHalalCategory.id,
      discount: 5,
      discountPrice: 42750,
    },
    {
      name: 'Perisa Rum Blackforest',
      slug: 'pasta-rum-blackforest',
      description: 'Pasta perisa rum blackforest untuk cake premium. Belum bersertifikat halal.',
      price: 46000,
      stock: 100,
      featured: false,
      brand: 'Golden Brown',
      sku: 'GB-RUMBLACKFOREST-30',
      weight: 0.03,
  image: '/assets/products/100g/Rum Blackforest.png',
      categoryId: nonHalalCategory.id,
      discount: 5,
      discountPrice: 43700,
    },
    {
      name: 'Perisa Rum Buttercream',
      slug: 'pasta-rum-buttercream',
      description: 'Pasta perisa rum untuk buttercream dengan aroma kuat. Belum bersertifikat halal.',
      price: 45500,
      stock: 100,
      featured: false,
      brand: 'Golden Brown',
      sku: 'GB-RUMBUTTERCREAM-30',
      weight: 0.03,
  image: '/assets/products/100g/Rum Buttercream.png',
      categoryId: nonHalalCategory.id,
      discount: 5,
      discountPrice: 43225,
    },
    {
      name: 'Perisa Rum Jamaica',
      slug: 'pasta-rum-jamaica',
      description: 'Pasta perisa rum jamaica premium untuk kreasi cake eksklusif. Belum bersertifikat halal.',
      price: 47000,
      stock: 100,
      featured: true,
      brand: 'Golden Brown',
      sku: 'GB-RUMJAMAICA-30',
      weight: 0.03,
  image: '/assets/products/100g/Rum Jamaica.png',
      categoryId: nonHalalCategory.id,
      discount: 5,
      discountPrice: 44650,
    },
    {
      name: 'Perisa Rum Pasta',
      slug: 'pasta-rum-pasta',
      description: 'Pasta perisa rum standar untuk berbagai kreasi bakery. Belum bersertifikat halal.',
      price: 44000,
      stock: 100,
      featured: false,
      brand: 'Golden Brown',
      sku: 'GB-RUMPASTA-30',
      weight: 0.03,
  image: '/assets/products/100g/Rum Pasta.png',
      categoryId: nonHalalCategory.id,
      discount: 5,
      discountPrice: 41800,
    },
    {
      name: 'Perisa Rum Semprot',
      slug: 'pasta-rum-semprot',
      description: 'Pasta perisa rum untuk spray application. Belum bersertifikat halal.',
      price: 46000,
      stock: 100,
      featured: false,
      brand: 'Golden Brown',
      sku: 'GB-RUMSEMPROT-30',
      weight: 0.03,
  image: '/assets/products/100g/Rum Semprot.png',
      categoryId: nonHalalCategory.id,
      discount: 5,
      discountPrice: 43700,
    },
    {
      name: 'Perisa Vanila dan Pewarna',
      slug: 'pasta-vanila',
      description: 'Pasta perisa vanila standar untuk berbagai kreasi cake dan bakery. Belum bersertifikat halal.',
      price: 38000,
      stock: 100,
      featured: true,
      brand: 'Golden Brown',
      sku: 'GB-VANILLA-30',
      weight: 0.03,
  image: '/assets/products/30g/Vanila.png',
      categoryId: nonHalalCategory.id,
      discount: 5,
      discountPrice: 36100,
    },
    {
      name: 'Perisa Vanilla Crown dan Pewarna',
      slug: 'pasta-vanilla-crown',
      description: 'Pasta perisa vanilla premium grade dengan aroma vanilla yang kuat. Belum bersertifikat halal.',
      price: 40000,
      stock: 100,
      featured: true,
      brand: 'Golden Brown',
      sku: 'GB-VANILLACROWN-30',
      weight: 0.03,
  image: '/assets/products/30g/Vanilla Crown.png',
      categoryId: nonHalalCategory.id,
      discount: 5,
      discountPrice: 38000,
    },
  ]

  for (const product of products) {
    await prisma.product.upsert({
      where: { slug: product.slug },
      update: {
        name: product.name,
        description: product.description,
        price: product.price,
        stock: product.stock,
        featured: product.featured,
        image: product.image,
        brand: product.brand,
        sku: product.sku,
        weight: product.weight,
        categoryId: product.categoryId,
        discount: product.discount,
        discountPrice: product.discountPrice,
      },
      create: product,
    })
  }

  console.log('Products created:', products.length)
  console.log('  - Halal products: 37')
  console.log('  - Non-halal products: 8')
  console.log('Seed completed successfully!')
}

main()
  .catch((e) => {
    console.error('Error during seed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
